title: My Blog
description: Welcome to my coding blog where I share tutorials, projects, and thoughts about development.
baseurl: ""
url: "https://timsonner.github.io"

# Author information
author:
  name: Your Name
  email: your.email@example.com

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Kramdown settings for better code highlighting
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Collections (if you want to organize content)
collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Your Name"
